---
- name: Configure Proxmox Host
  hosts: localhost
  become: yes
  gather_facts: yes

  vars:
    swappiness: 10
    ssh_key: /.ssh/id_ed25519
    vfio_modules:
      - vfio
      - vfio_iommu_type1
      - vfio_pci

  tasks:

    - name: Set vm.swappiness
      sysctl:
        name: vm.swappiness
        value: "{{ swappiness }}"
        state: present
        reload: yes
    
    - name: Generate SSH key for host
      openssh_keypair:
        path: "{{ ansible_env.HOME }}{{ ssh_key }}"
        type: ed25519
        force: no   # prevents overwriting existing key

    - name: Ensure IOMMU enabled in GRUB
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 intel_iommu=on"'
        backrefs: yes
      when: ansible_facts['processor_cores'] > 0
      notify: update grub

    - name: Ensure VFIO kernel modules loaded
      copy:
        dest: /etc/modules-load.d/vfio.conf
        content: |
          {% for mod in vfio_modules %}
          {{ mod }}
          {% endfor %}

  handlers:
    - name: update grub
      command: update-grub
      become: yes
