---
- name: Configure Proxmox Host for PCI(e) Passthrough
  hosts: localhost
  connection: local
  become: yes
  gather_facts: yes
  environment:
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: false

  vars:
    # Basic system configuration
    swappiness: 10
    ssh_key: .ssh/id_ed25519

    # PCIe Passthrough configuration
    pci_passthrough: true
    process_pci_device_path: "pci-process-device.yml"

    # Devices to configure for passthrough (search strings)
    passthrough_devices:
      - "SAS2308"           # LSI SAS controller
      # - "ConnectX-3"        # Mellanox network card

    # VFIO kernel modules
    vfio_modules:
      - vfio
      - vfio_iommu_type1
      - vfio_pci

    # Kernel parameters for IOMMU
    kernel_params: "intel_iommu=on iommu=pt"

  tasks:
    # ===== Configuration Display =====
    - name: Display current configuration
      debug:
        msg:
          - "Swappiness: {{ swappiness }}"
          - "SSH Key: {{ ssh_key }}"
          - "PCIe Passthrough: {{ pci_passthrough }}"
          - "Passthrough devices: {{ passthrough_devices }}"
          - "VFIO modules: {{ vfio_modules }}"
          - "Kernel parameters: {{ kernel_params }}"

    # ===== General System Setup =====
    - name: Configure VM swappiness
      sysctl:
        name: vm.swappiness
        value: "{{ swappiness }}"
        state: present
        reload: yes

    - name: Generate SSH key pair for host
      openssh_keypair:
        path: "{{ ansible_env.HOME }}/{{ ssh_key }}"
        type: ed25519
        force: no

    # ===== GRUB Configuration =====
    - name: Read current GRUB configuration
      slurp:
        src: /etc/default/grub
      register: grub_content

    - name: Parse GRUB configuration
      set_fact:
        grub_config: "{{ grub_content.content | b64decode }}"
        grub_has_params: "{{ (grub_content.content | b64decode) | regex_search(kernel_params) is not none }}"

    - name: Enable IOMMU in GRUB configuration
      lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 {{ kernel_params }}"'
        backrefs: yes
      notify: update-grub
      when: pci_passthrough and not grub_has_params

    - name: Remove IOMMU kernel parameters from GRUB
      replace:
        path: /etc/default/grub
        regexp: '\s*{{ kernel_params | regex_escape }}'
        replace: ''
      notify: update-grub
      when: not pci_passthrough

    # ===== VFIO Module Configuration =====
    - name: Configure VFIO kernel modules for loading
      copy:
        dest: /etc/modules-load.d/vfio.conf
        content: |
          # VFIO modules for PCIe passthrough
          {% for mod in vfio_modules %}
          {{ mod }}
          {% endfor %}
        backup: yes
      notify: update-initramfs
      when: pci_passthrough

    - name: Remove VFIO kernel modules configuration
      file:
        path: /etc/modules-load.d/vfio.conf
        state: absent
      notify: update-initramfs
      when: not pci_passthrough

    # ===== PCIe Device Discovery =====
    - name: Discover PCI devices
      command: lspci -nn
      register: pci_list
      changed_when: false
      when: pci_passthrough

    - name: Get PCI device drivers
      command: lspci -k
      register: pci_drivers
      changed_when: false
      when: pci_passthrough

    - name: Initialize device tracking variables
      set_fact:
        pci_ids: []
        blacklist_drivers: []
      when: pci_passthrough

    # ===== Process Each Passthrough Device =====
    - name: Process passthrough devices
      include_tasks: "{{ process_pci_device_path }}"
      loop: "{{ passthrough_devices }}"
      loop_control:
        label: "{{ item }}"
      when: pci_passthrough

    # ===== Configure Device Binding =====
    - name: Bind PCI devices to vfio-pci driver
      copy:
        dest: /etc/modprobe.d/vfio-pci.conf
        content: |
          # Bind specific PCI devices to vfio-pci for passthrough
          options vfio-pci ids={{ pci_ids | join(",") }}
        backup: yes
      notify: update-initramfs
      when: pci_passthrough and (pci_ids | length > 0)

    - name: Remove vfio-pci device binding
      file:
        path: /etc/modprobe.d/vfio-pci.conf
        state: absent
      notify: update-initramfs
      when: not pci_passthrough

    # ===== Driver Blacklist Configuration =====
    - name: Blacklist conflicting drivers
      copy:
        dest: /etc/modprobe.d/blacklist-passthrough.conf
        content: |
          # Blacklist drivers for PCIe passthrough devices
          {% for driver in (blacklist_drivers | unique) %}
          {% if driver %}
          blacklist {{ driver }}
          {% endif %}
          {% endfor %}
        backup: yes
      notify: update-initramfs
      when: pci_passthrough and (blacklist_drivers | select | length > 0)

    - name: Remove driver blacklist
      file:
        path: /etc/modprobe.d/blacklist-passthrough.conf
        state: absent
      notify: update-initramfs
      when: not pci_passthrough

    # # ===== Verify installation =====
    # - name: Gather passthrough config
    #   block:
    #     - name: Read GRUB kernel params
    #       command: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub
    #       register: grub_line
    #       changed_when: false
    #       failed_when: false

    #     - name: Read VFIO modules
    #       command: cat /etc/modules-load.d/vfio.conf
    #       register: vfio_mods
    #       changed_when: false
    #       failed_when: false

    #     - name: Read vfio-pci binding
    #       command: cat /etc/modprobe.d/vfio-pci.conf
    #       register: vfio_pci
    #       changed_when: false
    #       failed_when: false

    #     - name: Read blacklisted drivers
    #       command: cat /etc/modprobe.d/blacklist-passthrough.conf
    #       register: vfio_blacklist
    #       changed_when: false
    #       failed_when: false

    - name: Display completion message
      debug:
        msg:
          - "PCIe passthrough configuration completed"
          - "Found {{ pci_ids | length }} devices for passthrough"
          - "Blacklisted {{ blacklist_drivers | select | unique | length }} drivers"
          - "Reboot required to apply changes"
      when: pci_passthrough

  handlers:
    - name: update-grub
      command: update-grub

    - name: update-initramfs
      command: update-initramfs -u -k all