---
- name: Configure Proxmox Host for PCI(e) Passthrough
  hosts: localhost
  connection: local
  become: true
  gather_facts: true
  environment:
    ANSIBLE_DISPLAY_SKIPPED_HOSTS: false

  vars:
    # Basic system configuration
    swappiness: 10
    ssh_key: .ssh/id_ed25519

    # PCIe Passthrough configuration
    pci_passthrough: false
    process_pci_device_path: "pci-process-device.yml"

    # Devices to configure for passthrough (search strings)
    passthrough_devices:
      - "SAS2308"           # LSI SAS controller
      # - "ConnectX-3"        # Mellanox network card
      # - "Sandisk Corp WD PC SN810" # 2TB SSD. Currently the only nvme device. TODO: handle disks separately.

    # Drivers to never blacklist (host must keep access)
    drivers_whitelist:
      - nvme
      - ahci

    # VFIO kernel modules
    vfio_modules:
      - vfio
      - vfio_iommu_type1
      - vfio_pci

    # Kernel parameters for IOMMU
    kernel_params: "intel_iommu=on iommu=pt"

  tasks:
    # ===== Configuration Display =====
    - name: Display current configuration
      ansible.builtin.debug:
        msg:
          - "Swappiness: {{ swappiness }}"
          - "SSH Key: {{ ssh_key }}"
          - "PCIe Passthrough: {{ pci_passthrough }}"
          - "Passthrough devices: {{ passthrough_devices }}"
          - "VFIO modules: {{ vfio_modules }}"
          - "Kernel parameters: {{ kernel_params }}"

    # ===== General System Setup =====
    - name: Configure VM swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: "{{ swappiness }}"
        state: present
        reload: true

    - name: Generate SSH key pair for host
      community.crypto.openssh_keypair:
        path: "{{ ansible_env.HOME }}/{{ ssh_key }}"
        type: ed25519
        force: false

    # ===== GRUB Configuration =====
    - name: Read current GRUB configuration
      ansible.builtin.slurp:
        src: /etc/default/grub
      register: grub_content

    - name: Parse GRUB configuration
      ansible.builtin.set_fact:
        grub_config: "{{ grub_content.content | b64decode }}"
        grub_has_params: "{{ (grub_content.content | b64decode) | regex_search(kernel_params) is not none }}"

    - name: Enable IOMMU in GRUB configuration
      ansible.builtin.lineinfile:
        path: /etc/default/grub
        regexp: '^GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
        line: 'GRUB_CMDLINE_LINUX_DEFAULT="\1 {{ kernel_params }}"'
        backrefs: true
      notify: update-grub
      when: pci_passthrough and not grub_has_params

    - name: Remove IOMMU kernel parameters from GRUB
      ansible.builtin.replace:
        path: /etc/default/grub
        regexp: '\s*{{ kernel_params | regex_escape }}'
        replace: ''
      notify: update-grub
      when: not pci_passthrough

    # ===== VFIO Module Configuration =====
    - name: Configure VFIO kernel modules for loading
      ansible.builtin.copy:
        dest: /etc/modules-load.d/vfio.conf
        content: |
          # VFIO modules for PCIe passthrough
          {% for mod in vfio_modules %}
          {{ mod }}
          {% endfor %}
        backup: true
        mode: '0644'
      notify: update-initramfs
      when: pci_passthrough

    - name: Remove VFIO kernel modules configuration
      ansible.builtin.file:
        path: /etc/modules-load.d/vfio.conf
        state: absent
      notify: update-initramfs
      when: not pci_passthrough

    # ===== PCIe Device Discovery =====
    - name: Discover PCI devices
      ansible.builtin.command: lspci -nn
      register: pci_list
      changed_when: false
      when: pci_passthrough

    - name: Get PCI device drivers
      ansible.builtin.command: lspci -k
      register: pci_drivers
      changed_when: false
      when: pci_passthrough

    - name: Initialize device tracking variables
      ansible.builtin.set_fact:
        pci_ids: []
        blacklist_drivers: []
      when: pci_passthrough

    # ===== Process Each Passthrough Device =====
    - name: Process passthrough devices
      ansible.builtin.include_tasks: "{{ process_pci_device_path }}"
      loop: "{{ passthrough_devices }}"
      loop_control:
        label: "{{ item }}"
      when: pci_passthrough

    # ===== Configure Device Binding =====
    - name: Bind PCI devices to vfio-pci driver
      ansible.builtin.copy:
        dest: /etc/modprobe.d/vfio-pci.conf
        content: |
          # Bind specific PCI devices to vfio-pci for passthrough
          options vfio-pci ids={{ pci_ids | join(",") }}
        backup: true
        mode: '0644'
      notify: update-initramfs
      when: pci_passthrough and (pci_ids | length > 0)

    - name: Remove vfio-pci device binding
      ansible.builtin.file:
        path: /etc/modprobe.d/vfio-pci.conf
        state: absent
      notify: update-initramfs
      when: not pci_passthrough

    # ===== Driver Blacklist Configuration =====
    - name: Blacklist conflicting drivers
      ansible.builtin.copy:
        dest: /etc/modprobe.d/blacklist-passthrough.conf
        content: |
          # Blacklist drivers for PCIe passthrough devices
          {% for driver in (blacklist_drivers | unique) %}
          {% if driver %}
          blacklist {{ driver }}
          {% endif %}
          {% endfor %}
        backup: true
        mode: '0644'
      notify: update-initramfs
      when: pci_passthrough and (blacklist_drivers | select | length > 0)

    - name: Remove driver blacklist
      ansible.builtin.file:
        path: /etc/modprobe.d/blacklist-passthrough.conf
        state: absent
      notify: update-initramfs
      when: not pci_passthrough

    # # ===== Verify installation =====
    # - name: Gather passthrough config
    #   block:
    #     - name: Read GRUB kernel params
    #       ansible.builtin.command: grep GRUB_CMDLINE_LINUX_DEFAULT /etc/default/grub
    #       register: grub_line
    #       changed_when: false
    #       failed_when: false

    #     - name: Read VFIO modules
    #       ansible.builtin.command: cat /etc/modules-load.d/vfio.conf
    #       register: vfio_mods
    #       changed_when: false
    #       failed_when: false

    #     - name: Read vfio-pci binding
    #       ansible.builtin.command: cat /etc/modprobe.d/vfio-pci.conf
    #       register: vfio_pci
    #       changed_when: false
    #       failed_when: false

    #     - name: Read blacklisted drivers
    #       ansible.builtin.command: cat /etc/modprobe.d/blacklist-passthrough.conf
    #       register: vfio_blacklist
    #       changed_when: false
    #       failed_when: false

    - name: Display completion message
      ansible.builtin.debug:
        msg:
          - "PCIe passthrough configuration completed"
          - "Found {{ pci_ids | length }} devices for passthrough"
          - "Blacklisted {{ blacklist_drivers | select | unique | length }} drivers"
          - "Reboot required to apply changes"
      when: pci_passthrough

    # - name: Ensure keyring directory exists
    #   ansible.builtin.file:
    #     path: /etc/apt/keyrings
    #     state: directory
    #     mode: '0755'

    # - name: Add eza apt repository (Deb822 format)
    #   ansible.builtin.deb822_repository:
    #     name: gierens
    #     types: [deb]
    #     uris: http://deb.gierens.de
    #     suites: [stable]
    #     components: [main]
    #     signed_by: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    #     enabled: true
    #     state: present
    #     update_cache: true

    # - name: Install eza
    #   ansible.builtin.apt:
    #     name: eza
    #     state: present

  handlers:
    - name: update-grub
      ansible.builtin.command: update-grub
      changed_when: true

    - name: update-initramfs
      ansible.builtin.command: update-initramfs -u -k all
      changed_when: true