---
- name: Configure Docker VM
  hosts: all
  become: true
  gather_facts: true

  vars:
    bash_addons: true
    home_symlink: true

    install_packages: true
    autoremove_packages: true

    install_starship_from_git: true
    install_mergerfs_from_git: true

    disable_networkd_if_nm: true
    disable_services: true

    disable_autostart: true

    disable_compositing: true # When DE is installed

    swappiness_value: 10 # Default is typically 60

    deploy_arr_stack: true

    map_drives: true
    drive_mount_options: defaults,relatime,barrier=1,commit=60,errors=remount-ro
    pool_mount_options: defaults,allow_other,use_ino,category.create=epmfs,minfreespace=10G
    pre_mount_dirs:
      - /mnt/.pools
      - /mnt/.drives
    mount_drives:
      # Configs location (SATA with PLP)
      /mnt/.drives/sata1: scsi-0QEMU_QEMU_HARDDISK_INTEL_SSDSC2BB480G7-part1
      # Working area (large NVME)
      /mnt/.drives/nvme1: nvme-PC_SN810_NVMe_WDC_2048GB_2153J2440608-part1
      # Parity disks (Ultrastars, extra-durable)
      /mnt/.drives/parity1: ata-WDC_WUH721414ALE600_9JGDEENT-part1
      /mnt/.drives/parity2: ata-WDC_WUH721414ALE600_9JGMYJYT-part1
      # Data pool (Ultrastars, extra-durable)
      /mnt/.drives/hdd1: ata-WDC_WUH721414ALE600_9JGA3VJT-part1
      /mnt/.drives/hdd2: ata-WDC_WUH721414ALE600_9JGDEA0T-part1
      # Data pool (Toshiba N300s, 1/2 as durable as Ultrastars)
      /mnt/.drives/hdd3: ata-TOSHIBA_HDWG11A_49F0A01PFATG-part1
      /mnt/.drives/hdd4: ata-TOSHIBA_HDWG11A_49F0A025FATG-part1
    mount_pools:
      # Mergerfs pool (for HDDs)
      /mnt/.pools/hdds: /mnt/.drives/hdd1:/mnt/.drives/hdd2:/mnt/.drives/hdd3:/mnt/.drives/hdd4
    mount_dirs:
      /mnt/data: /mnt/.pools/hdds
      /mnt/config: /mnt/.drives/sata1
      /mnt/active: /mnt/.drives/nvme1

    packages:
      - openssh-server
      - hdparm
      - smartmontools
      - parted
      - snapraid
      - rename
      - mediainfo
      # - mergerfs # repo version outdated, get from git directly
      # Shell UX tools
      # - duf
      # - tldr
      # - micro
      # DE-related
      # - cinnamon-core
      # - gedit
      # - gnome-system-monitor
      # - file-roller
      # - gnome-disk-utility

    services_to_disable: []
      # DE-related
      # - wpa_supplicant.service
      # - blueman-mechanism.service
      # - power-profiles-daemon.service
      # - ModemManager.service

    networkd_services:
      - systemd-networkd.service
      - systemd-networkd-wait-online.service
      - systemd-network-generator.service
      - systemd-networkd.socket

    autostart_entries_to_disable: []
      # DE-related
      # - blueman.desktop
      # - org.gnome.SettingsDaemon.Power.desktop
      # - cinnamon-settings-daemon-power.desktop
      # - org.gnome.SettingsDaemon.Rfkill.desktop
      # - org.gnome.SettingsDaemon.Wwan.desktop
      # - org.gnome.SettingsDaemon.PrintNotifications.desktop
      # - cinnamon-settings-daemon-print-notifications.desktop
      # - org.gnome.SettingsDaemon.Smartcard.desktop
      # - cinnamon-settings-daemon-smartcard.desktop
      # - org.gnome.SettingsDaemon.Wacom.desktop
      # - cinnamon-settings-daemon-wacom.desktop
      # - pulseaudio.desktop
      # - xapp-sn-watcher.desktop
      # - xdg-user-dirs-kde.desktop
      # - at-spi-dbus-bus.desktop
      # - gnome-keyring-pkcs11.desktop


  tasks:
    - name: Set swappiness
      ansible.posix.sysctl:
        name: vm.swappiness
        value: "{{ swappiness_value }}"
        sysctl_set: true
        state: present
        reload: true

    - name: Mount drives and create directories for containers
      block:
        - name: Initialize directories
          ansible.builtin.file:
            path: "{{ item }}"
            state: directory # Not conditional so that existing directories with data aren't deleted
            mode: '0755'
          loop: "{{ pre_mount_dirs }}"
          loop_control:
            label: "{{ item }}"
          when: map_drives

        - name: Mount drives to sensible mount points
          ansible.posix.mount:
            src: "/dev/disk/by-id/{{ item.value }}"
            path: "{{ item.key }}"
            fstype: ext4
            opts: "{{ drive_mount_options }}"
            state: "{{ 'mounted' if map_drives else 'absent' }}"
          loop: "{{ mount_drives | dict2items }}"
          loop_control:
            label: "{{ item }}"
          # notify: reload-mounts

        - name: Mount mergerfs pools
          ansible.posix.mount:
            src: "{{ item.value }}"
            path: "{{ item.key }}"
            fstype: fuse.mergerfs
            opts: "{{ pool_mount_options }}"
            state: "{{ 'mounted' if map_drives else 'absent' }}"
          loop: "{{ mount_pools | dict2items }}"
          loop_control:
            label: "{{ item }}"
          # notify: reload-mounts

        - name: Mount directories for use by apps
          ansible.posix.mount:
            src: "{{ item.value }}"
            path: "{{ item.key }}"
            fstype: none
            opts: bind
            state: "{{ 'mounted' if map_drives else 'absent' }}"
          loop: "{{ mount_dirs | dict2items}}"
          loop_control:
            label: "{{ item }}"
          # notify: reload-mounts

    - name: Ensure /home/root points to /root
      ansible.builtin.file:
        src: /root
        dest: /home/root
        state: "{{ 'link' if home_symlink else 'absent' }}"

    - name: Add history search and LS customizations to .bashrc
      ansible.builtin.blockinfile:
        path: /home/{{ ansible_user }}/.bashrc
        block: |
          # History search and LS customization
          bind '"\e[A": history-search-backward'

          export TIME_FORMAT=" %y-%b-%d, %I:%M:%S %p "

          export LS_OPTIONS='--group-directories-first --color=auto --hyperlink=auto --time-style=+"$TIME_FORMAT" --si -Gg -C'
          eval "$(dircolors)"
          alias lsc="ls $LS_OPTIONS"
          alias l=lsc
          alias ll="lsc $LS_OPTIONS -l"
          alias la="lsc $LS_OPTIONS -la"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        create: true
        mode: '0644'
        state: "{{ 'present' if bash_addons else 'absent' }}"

    - name: Install base packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: "{{ 'present' if install_packages else 'absent' }}"
        purge: true
        update_cache: true

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: true
        purge: true
      when: autoremove_packages

    - name: Gather NetworkManager status
      ansible.builtin.systemd_service:
        name: NetworkManager.service
      register: nm_status

    - name: Disable systemd-networkd services if NetworkManager active
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: "{{ 'stopped' if disable_networkd_if_nm else 'started' }}"
        enabled: "{{ false if disable_networkd_if_nm else true }}"
      loop: "{{ networkd_services }}"
      when: nm_status.status is defined and nm_status.status.ActiveState == 'active'

    - name: Disable unneeded services
      ansible.builtin.systemd_service:
        name: "{{ item }}"
        state: "{{ 'stopped' if disable_services else 'started' }}"
        enabled: "{{ false if disable_services else true }}"
      loop: "{{ services_to_disable }}"

    - name: Disable unneeded autostart entries
      ansible.builtin.lineinfile:
        path: "/etc/xdg/autostart/{{ item }}"
        line: "Hidden=true"
        state: "{{ 'present' if disable_autostart else 'absent' }}"
        create: false
        insertafter: EOF
      loop: "{{ autostart_entries_to_disable }}"

    - name: Enable or disable Cinnamon compositing
      ansible.builtin.command: >
        gsettings set org.cinnamon.muffin compositing-manager
        {{ 'false' if disable_compositing else 'true' }}
      become_user: "{{ ansible_user | default(ansible_env.USER) }}"
      changed_when: true
      when: ansible_env.XDG_CURRENT_DESKTOP is defined and 'Cinnamon' in ansible_env.XDG_CURRENT_DESKTOP

    - name: Ensure mergerfs installed or removed
      block:
        - name: Get latest mergerfs Debian URL
          ansible.builtin.uri:
            url: https://api.github.com/repos/trapexit/mergerfs/releases/latest
            return_content: true
          register: mergerfs_releases
          when: install_mergerfs_from_git

        - name: Set mergerfs download URL
          ansible.builtin.set_fact:
            mergerfs_url: "{{ mergerfs_releases.json.assets
              | selectattr('name','search','debian-bookworm_amd64.deb')
              | map(attribute='browser_download_url')
              | first }}"
          when: install_mergerfs_from_git

        - name: Log mergerfs download url
          ansible.builtin.debug:
            msg: "Downloading and installing: {{ mergerfs_url }}"
          when: install_mergerfs_from_git

        - name: Download and install mergerfs
          ansible.builtin.apt:
            deb: "{{ mergerfs_url }}"
          when: install_mergerfs_from_git

        - name: Ensure mergerfs package state
          ansible.builtin.apt:
            name: mergerfs
            state: "{{ 'present' if install_mergerfs_from_git else 'absent' }}"

    - name: Ensure Starship installed or removed
      block:
        - name: Get latest Starship release info
          ansible.builtin.uri:
            url: https://api.github.com/repos/starship/starship/releases/latest
            return_content: true
          register: starship_release
          when: install_starship_from_git

        - name: Set Starship download URL (Linux x86_64 musl)
          ansible.builtin.set_fact:
            starship_url: "{{ starship_release.json.assets
              | selectattr('name','search','x86_64-unknown-linux-musl.tar.gz')
              | map(attribute='browser_download_url')
              | first }}"
          when: install_starship_from_git

        - name: Log starship download url
          ansible.builtin.debug:
            msg: "Downloading and installing: {{ starship_url }}"
          when: install_starship_from_git

        - name: Download and install Starship
          ansible.builtin.unarchive:
            src: "{{ starship_url }}"
            dest: /usr/local/bin
            remote_src: true
            mode: '0755'
          when: install_starship_from_git

        - name: Ensure Starship binary state
          ansible.builtin.file:
            path: /usr/local/bin/starship
            state: "{{ 'file' if install_starship_from_git else 'absent' }}"
            mode: '0755'

        - name: Ensure Starship init line in .bashrc
          ansible.builtin.lineinfile:
            path: /home/{{ ansible_user }}/.bashrc
            line: 'eval "$(starship init bash)"'
            state: "{{ 'present' if install_starship_from_git else 'absent' }}"
            search_string: 'eval "$(starship init bash)"'

    - name: Ensure keyring directory exists
      ansible.builtin.file:
        path: /etc/apt/keyrings
        state: directory
        mode: '0755'

    - name: Add eza apt repository (Deb822 format)
      ansible.builtin.deb822_repository:
        name: gierens
        types: [deb]
        uris: http://deb.gierens.de
        suites: [stable]
        components: [main]
        signed_by: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
        enabled: true
        state: present
      register: eza_repo

    - name: Update apt cache after adding eza repository
      ansible.builtin.apt:
        update_cache: true
      when: eza_repo is changed

    - name: Install eza
      ansible.builtin.apt:
        name: eza
        state: present



  handlers:
    - name: reload-mounts
      ansible.builtin.command: mount -av
      changed_when: true

    - name: update-initramfs
      ansible.builtin.command: update-initramfs -u -k all
      changed_when: true