---
- name: VM Setup Playbook
  hosts: all
  become: yes
  gather_facts: yes

  vars:
    bash_addons: true
    home_symlink: true

    install_packages: true
    autoremove_packages: true

    install_starship_from_git: true
    install_mergerfs_from_git: true

    disable_networkd_if_nm: true
    disable_services: true

    disable_autostart: true

    disable_compositing: true # When DE is installed

    swappiness_value: 10 # Default is typically 60

    packages:
      - openssh-server
      - hdparm
      - smartmontools
      - snapraid
      # - mergerfs # repo version outdated, get from git directly
      # DE-related
      # - cinnamon-core
      # - gedit
      # - gnome-system-monitor
      # - file-roller
      # - gnome-disk-utility

    services_to_disable: []
      # DE-related
      # - wpa_supplicant.service
      # - blueman-mechanism.service
      # - power-profiles-daemon.service
      # - ModemManager.service

    networkd_services:
      - systemd-networkd.service
      - systemd-networkd-wait-online.service
      - systemd-network-generator.service
      - systemd-networkd.socket

    autostart_entries_to_disable:
      # DE-related
      - blueman.desktop
      - org.gnome.SettingsDaemon.Power.desktop
      - cinnamon-settings-daemon-power.desktop
      - org.gnome.SettingsDaemon.Rfkill.desktop
      - org.gnome.SettingsDaemon.Wwan.desktop
      - org.gnome.SettingsDaemon.PrintNotifications.desktop
      - cinnamon-settings-daemon-print-notifications.desktop
      - org.gnome.SettingsDaemon.Smartcard.desktop
      - cinnamon-settings-daemon-smartcard.desktop
      - org.gnome.SettingsDaemon.Wacom.desktop
      - cinnamon-settings-daemon-wacom.desktop
      - pulseaudio.desktop
      - xapp-sn-watcher.desktop
      - xdg-user-dirs-kde.desktop
      - at-spi-dbus-bus.desktop
      - gnome-keyring-pkcs11.desktop


  tasks:
    - name: Set swappiness
      ansible.builtin.sysctl:
        name: vm.swappiness
        value: "{{ swappiness_value }}"
        sysctl_set: yes
        state: present
        reload: yes

    - name: Ensure /home/root points to /root
      ansible.builtin.file:
        src: /root
        dest: /home/root
        state: "{{ 'link' if home_symlink else 'absent' }}"

    - name: Add history search and LS customizations to .bashrc
      ansible.builtin.blockinfile:
        path: /home/{{ ansible_user }}/.bashrc
        block: |
          # History search and LS customization
          bind '"\e[A": history-search-backward'

          export TIME_FORMAT=" %y-%b-%d, %I:%M:%S %p "

          export LS_OPTIONS='--group-directories-first --color=auto --hyperlink=auto --time-style=+"$TIME_FORMAT" --si -Gg -C'
          eval "$(dircolors)"
          alias lsc="ls $LS_OPTIONS"
          alias l=lsc
          alias ll="lsc $LS_OPTIONS -l"
          alias la="lsc $LS_OPTIONS -la"
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"
        create: yes
        state: "{{ 'present' if bash_addons else 'absent' }}"

    - name: Install base packages
      ansible.builtin.apt:
        name: "{{ packages }}"
        state: "{{ 'present' if install_packages else 'absent' }}"
        purge: yes

    - name: Remove unused packages
      ansible.builtin.apt:
        autoremove: yes
        purge: yes
      when: autoremove_packages

    - name: Gather NetworkManager status
      ansible.builtin.systemd:
        name: NetworkManager.service
      register: nm_status

    - name: Disable systemd-networkd services if NetworkManager active
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: "{{ 'stopped' if disable_networkd_if_nm else 'started' }}"
        enabled: "{{ 'no' if disable_networkd_if_nm else 'yes' }}"
      loop: "{{ networkd_services }}"
      when: nm_status.status is defined and nm_status.status.ActiveState == 'active'

    - name: Disable unneeded services
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: "{{ 'stopped' if disable_services else 'started' }}"
        enabled: "{{ 'no' if disable_services else 'yes' }}"
      loop: "{{ services_to_disable }}"

    - name: Disable unneeded autostart entries
      ansible.builtin.lineinfile:
        path: "/etc/xdg/autostart/{{ item }}"
        line: "Hidden=true"
        state: "{{ 'absent' if disable_autostart else 'present' }}"
        create: no
        insertafter: EOF
      loop: "{{ autostart_entries_to_disable }}"

    - name: Enable or disable Cinnamon compositing
      ansible.builtin.command: >
        gsettings set org.cinnamon.muffin compositing-manager
        {{ 'false' if disable_compositing else 'true' }}
      become_user: "{{ ansible_user | default(ansible_env.USER) }}"
      when: ansible_env.XDG_CURRENT_DESKTOP is defined and 'Cinnamon' in ansible_env.XDG_CURRENT_DESKTOP

    - name: Ensure mergerfs installed or removed
      block:
        - name: Get latest mergerfs Debian URL
          ansible.builtin.uri:
            url: https://api.github.com/repos/trapexit/mergerfs/releases/latest
            return_content: yes
          register: mergerfs_releases
          when: install_mergerfs_from_git

        - name: Set mergerfs download URL
          set_fact:
            mergerfs_url: "{{ mergerfs_releases.json.assets
              | selectattr('name','search','debian-bookworm_amd64.deb')
              | map(attribute='browser_download_url')
              | first }}"
          when: install_mergerfs_from_git

        - name: Log mergerfs download url
          debug:
            msg: "Downloading and installing: {{ mergerfs_url }}"
          when: install_mergerfs_from_git

        - name: Download and install mergerfs
          ansible.builtin.apt:
            deb: "{{ mergerfs_url }}"
          when: install_mergerfs_from_git

        - name: Ensure mergerfs package state
          ansible.builtin.apt:
            name: mergerfs
            state: "{{ 'present' if install_mergerfs_from_git else 'absent' }}"

    - name: Ensure Starship installed or removed
      block:
        - name: Get latest Starship release info
          ansible.builtin.uri:
            url: https://api.github.com/repos/starship/starship/releases/latest
            return_content: yes
          register: starship_release
          when: install_starship_from_git

        - name: Set Starship download URL (Linux x86_64 musl)
          set_fact:
            starship_url: "{{ starship_release.json.assets
              | selectattr('name','search','x86_64-unknown-linux-musl.tar.gz')
              | map(attribute='browser_download_url')
              | first }}"
          when: install_starship_from_git

        - name: Log starship download url
          debug:
            msg: "Downloading and installing: {{ starship_url }}"
          when: install_starship_from_git

        - name: Download and install Starship
          ansible.builtin.unarchive:
            src: "{{ starship_url }}"
            dest: /usr/local/bin
            remote_src: yes
          when: install_starship_from_git

        - name: Ensure Starship binary state
          ansible.builtin.file:
            path: /usr/local/bin/starship
            state: "{{ 'file' if install_starship_from_git else 'absent' }}"

        - name: Ensure Starship init line in .bashrc
          ansible.builtin.lineinfile:
            path: /home/{{ ansible_user }}/.bashrc
            line: 'eval "$(starship init bash)"'
            state: "{{ 'present' if install_starship_from_git else 'absent' }}"
            search_string: 'eval "$(starship init bash)"'